name: modelport_workspace
publish_to: none

environment:
  sdk: ^3.8.0

workspace:
  - packages/modelport
  - packages/modelport_flutter
  - packages/modelport_onnx
  - packages/modelport_onnx/example

dev_dependencies:
  lints: ^6.0.0
