name: modelport_workspace
publish_to: none

environment:
  sdk: ^3.8.0

workspace:
  - packages/modelport
  - packages/modelport_flutter
  - packages/modelport_onnx
  - packages/modelport_onnx/example
  - packages/modelport_executorch
  - packages/modelport_executorch/example
  - packages/modelport_llamacpp
  - packages/modelport_llamacpp/example
  - apps/demo

dev_dependencies:
  lints: ^6.0.0
