import shutil
from pathlib import Path

import pytest
from typer.testing import CliRunner

from modelport.cli import app
from modelport.codegen.dart import (
    class_name,
    file_name,
    format_with_dart,
    generate_dart,
    member_name,
)
from modelport.errors import ModelPortError
from modelport.manifest import Manifest

REPO = Path(__file__).resolve().parents[3]
TOY = REPO / "dart" / "packages" / "modelport" / "test" / "fixtures" / "toy_bundle"
GENERATED = REPO / "dart" / "packages" / "modelport" / "test" / "generated" / "toy_rgb.dart"
EXAMPLES = REPO / "spec" / "examples"


@pytest.mark.parametrize(
    ("model_id", "expected"),
    [
        ("mobilenet_v3_small", "MobilenetV3Small"),
        ("qwen2.5-0.5b", "Qwen2505b"),
        ("3d-net", "Model3dNet"),
    ],
)
def test_class_name(model_id, expected):
    assert class_name(model_id) == expected


@pytest.mark.parametrize(
    ("tensor", "expected"),
    [
        ("pixel_values", "pixelValues"),
        ("logits", "logits"),
        ("in", "in_"),
        ("0", "t0"),
        ("x.y", "xY"),
    ],
)
def test_member_name(tensor, expected):
    assert member_name(tensor) == expected


def test_file_name():
    assert file_name("qwen2.5-0.5b") == "qwen2_5_0_5b.dart"


def test_classifier_wrapper_has_named_tensors():
    source = generate_dart(
        Manifest.from_file(EXAMPLES / "image-classification.json"), location="hf://o/m"
    )
    assert "class MobilenetV3SmallModel" in source
    assert "static const defaultLocation = 'hf://o/m';" in source
    assert "required Tensor pixelValues" in source
    assert "logits: outputs['logits']!" in source


def test_detector_wrapper_has_every_output():
    source = generate_dart(Manifest.from_file(EXAMPLES / "object-detection.json"))
    assert "String location, {" in source
    assert "final Tensor output;" in source


def test_language_models_are_refused():
    with pytest.raises(ModelPortError, match="TextGenerator"):
        generate_dart(Manifest.from_file(EXAMPLES / "text-generation.json"))


@pytest.mark.skipif(shutil.which("dart") is None, reason="needs the Dart SDK")
def test_committed_dart_fixture_is_up_to_date():
    formatted = format_with_dart(generate_dart(Manifest.from_file(TOY / "modelport.json")))
    hint = f"Regenerate with: uv run modelport gen-dart {TOY} -o {GENERATED.parent}"
    assert formatted == GENERATED.read_text(encoding="utf-8"), hint


def test_cli_writes_the_file(tmp_path):
    result = CliRunner().invoke(app, ["gen-dart", str(TOY), "-o", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert (tmp_path / "toy_rgb.dart").read_text(encoding="utf-8").startswith("// Generated by")


def test_cli_refuses_language_models(tmp_path):
    result = CliRunner().invoke(
        app, ["gen-dart", str(EXAMPLES / "text-generation.json"), "-o", str(tmp_path)]
    )
    assert result.exit_code == 1
