"""Generate a typed Dart wrapper for a tensor model's inputs and outputs.

The wrapper turns tensor names into named parameters and fields, so a typo in an
input name is a compile error instead of a runtime one.
"""

from __future__ import annotations

import re

from ..errors import ModelPortError
from ..manifest import InputSpec, Manifest, OutputSpec, Task, TensorSpec

# Dart keywords and built-in identifiers that cannot be parameter or field names.
_RESERVED = set(
    [
        "abstract",
        "as",
        "assert",
        "async",
        "await",
        "base",
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "covariant",
        "default",
        "deferred",
        "do",
        "dynamic",
        "else",
        "enum",
        "export",
        "extends",
        "extension",
        "external",
        "factory",
        "false",
        "final",
        "finally",
        "for",
        "function",
        "get",
        "hide",
        "if",
        "implements",
        "import",
        "in",
        "interface",
        "is",
        "late",
        "library",
        "mixin",
        "new",
        "null",
        "of",
        "on",
        "operator",
        "part",
        "required",
        "rethrow",
        "return",
        "sealed",
        "set",
        "show",
        "static",
        "super",
        "switch",
        "sync",
        "this",
        "throw",
        "true",
        "try",
        "type",
        "typedef",
        "var",
        "void",
        "when",
        "while",
        "with",
        "yield",
    ]
)


def _words(text: str) -> list[str]:
    return [w for w in re.split(r"[^A-Za-z0-9]+", text) if w]


def class_name(model_id: str) -> str:
    """'mobilenet_v3_small' -> 'MobilenetV3Small'."""
    name = "".join(w[:1].upper() + w[1:] for w in _words(model_id))
    return name if name[:1].isalpha() else f"Model{name}"


def member_name(tensor: str) -> str:
    """'pixel_values' -> 'pixelValues'."""
    words = _words(tensor) or ["value"]
    name = words[0][:1].lower() + words[0][1:] + "".join(w[:1].upper() + w[1:] for w in words[1:])
    if not name[:1].isalpha():
        name = f"t{name}"
    return f"{name}_" if name in _RESERVED else name


def file_name(model_id: str) -> str:
    """'qwen2.5-0.5b' -> 'qwen2_5_0_5b.dart'."""
    return "_".join(w.lower() for w in _words(model_id)) + ".dart"


def _doc(spec: TensorSpec) -> str:
    # Backticks keep dartdoc from reading the shape as a reference.
    return f"`{spec.name}`: {spec.dtype.value} `{spec.shape}`"


def _unique(names: list[str], what: str) -> None:
    if len(set(names)) != len(names):
        raise ModelPortError(f"two {what} names map to the same Dart name: {names}")


def generate_dart(manifest: Manifest, *, location: str | None = None) -> str:
    """Dart source for a typed wrapper around `TensorModel`."""
    if manifest.task is Task.TEXT_GENERATION:
        raise ModelPortError("text-generation models have no tensors; use TextGenerator in Dart")
    name = class_name(manifest.id)
    inputs: list[InputSpec] = list(manifest.inputs)
    outputs: list[OutputSpec] = list(manifest.outputs)
    in_names = [member_name(i.name) for i in inputs]
    out_names = [member_name(o.name) for o in outputs]
    _unique(in_names, "input")
    _unique(out_names, "output")

    lines: list[str] = [
        f"// Generated by `modelport gen-dart` from {manifest.id} {manifest.version}.",
        "// Do not edit by hand; run gen-dart again after the manifest changes.",
        "",
        "import 'package:modelport/modelport.dart';",
        "",
        f"/// Typed access to {manifest.name or manifest.id} ({manifest.task.value}).",
    ]
    if manifest.description:
        lines.append(f"///\n/// {manifest.description}")
    lines += [f"class {name}Model {{", f"  {name}Model._(this.model);", ""]
    if location is not None:
        lines += [
            "  /// Where the bundle is published.",
            f"  static const defaultLocation = '{location}';",
            "",
        ]
    for spec, member in zip(inputs, in_names, strict=True):
        lines += [
            f"  /// Shape of input {_doc(spec)}.",
            f"  static const {member}Shape = <int>{spec.shape};",
            "",
        ]

    lines.append("  /// Downloads (if needed), verifies, and opens the model.")
    if location is not None:
        lines += [f"  static Future<{name}Model> load({{", "    String location = defaultLocation,"]
    else:
        lines += [f"  static Future<{name}Model> load(", "    String location, {"]
    lines += [
        "    String? variantId,",
        "    void Function(DownloadProgress)? onProgress,",
        "  }) async =>",
        f"      {name}Model._(",
        "        await ModelPort.load(location, variantId: variantId, onProgress: onProgress),",
        "      );",
        "",
        "  /// The underlying model, for golden checks and raw access.",
        "  final TensorModel model;",
        "",
        "  /// Runs the model.",
        "  ///",
    ]
    for spec in inputs:
        lines.append(f"  /// * {_doc(spec)}")
    params = "".join(f"required Tensor {m}, " for m in in_names).rstrip(", ")
    lines += [
        f"  Future<{name}Outputs> run({{{params}}}) async {{",
        "    final outputs = await model.run({",
    ]
    for spec, member in zip(inputs, in_names, strict=True):
        lines.append(f"      '{spec.name}': {member},")
    lines += ["    });", f"    return {name}Outputs("]
    for spec, member in zip(outputs, out_names, strict=True):
        lines.append(f"      {member}: outputs['{spec.name}']!,")
    lines += ["    );", "  }", "", "  Future<void> close() => model.close();", "}", ""]

    lines += [
        f"/// Outputs of {name}Model.run.",
        f"class {name}Outputs {{",
        f"  const {name}Outputs({{",
    ]
    for member in out_names:
        lines.append(f"    required this.{member},")
    lines += ["  });", ""]
    for spec, member in zip(outputs, out_names, strict=True):
        lines += [f"  /// {_doc(spec)}.", f"  final Tensor {member};", ""]
    lines[-1] = "}"
    return "\n".join(lines) + "\n"


def format_with_dart(source: str) -> str | None:
    """Format Dart source with `dart format`, or return None if Dart is not installed."""
    import shutil
    import subprocess
    import tempfile
    from pathlib import Path

    dart = shutil.which("dart")
    if dart is None:
        return None
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "generated.dart"
        path.write_text(source, encoding="utf-8")
        result = subprocess.run(
            [dart, "format", "--output=write", str(path)],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            raise ModelPortError(f"dart format failed on generated code:\n{result.stderr}")
        return path.read_text(encoding="utf-8")
